SELECT
  ID_PONTO_VENDA,
  COUNT(*) AS QTD_PRESENCA
FROM
  `involves-422612.involves_datasets.involves-dataset`
WHERE
  EXTRACT(YEAR
  FROM
    DATA) = 2020
  AND EXTRACT(MONTH
  FROM
    DATA) = 9
  AND VALOR = 'SIM'
GROUP BY
  ID_PONTO_VENDA
ORDER BY
  ID_PONTO_VENDA,
  QTD_PRESENCA DESC;
