SELECT
  PDV_UNIDADES.NOME_PONTO_VENDA,
  COALESCE(VISITAS_COUNT.TOTAL_VISITAS, 0) AS TOTAL_VISITAS
FROM
  `involves-422612.involves_datasets.involves-dataset` AS PDV_UNIDADES
LEFT JOIN (
  SELECT
    FK_PDV,
    COUNT(ID_VISITA) AS TOTAL_VISITAS
  FROM
    `involves-422612.involves_datasets.involves-dataset-visitas`
  WHERE
    FL_VISITADO = 1
  GROUP BY
    FK_PDV) AS VISITAS_COUNT
ON
  PDV_UNIDADES.ID_PONTO_VENDA = VISITAS_COUNT.FK_PDV
WHERE
  NOME_PONTO_VENDA = 'INVOLVES'
GROUP BY
  PDV_UNIDADES.NOME_PONTO_VENDA,
  TOTAL_VISITAS;